-- Exam OCA 3

-- 1. C

-- 2. D

SELECT last_name, job_id, salary FROM employees
WHERE JOB_ID IN ('SA_REP','MK_MAN')
AND SALARY BETWEEN 1000 AND 19000;

-- 3. A, C
SELECT * FROM employees 
WHERE JOB_ID IN ('SA_REP','MK_MAN');

-- 4. B
SELECT DEPARTMENT_NAME FROM DEPARTMENTS
WHERE DEPARTMENT_NAME LIKE '%er%';

-- 5. A, D

SELECT * FROM employees
WHERE COMMISSION_PCT IS NULL;

SELECT * FROM employees
WHERE NOT(COMMISSION_PCT IS NOT NULL);

-- 6.
SELECT * FROM employees
WHERE SALARY <=5000 AND SALARY >=2000;

SELECT * FROM employees
WHERE SALARY BETWEEN 2000 AND 5000;



SELECT FIRST_NAME, '&JOB'
FROM EMPLOYEES
WHERE JOB_ID LIKE '%'||&JOB||'%'
AND '&&JOB' BETWEEN 'A' AND 'Z';


SELECT NEXT_DAY('01-JAN-2009','mit') FROM DUAL;






